name: dynamodb

on:
  push:
    branches: [ dynamodb ]

jobs:
  testGeneral:
    name: General test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go env
      uses: actions/setup-go@v5
      with:
        go-version: ^1.13
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Test
      run: |
        go test -v -count 1 -p 1 -cover -coverprofile=coverage_general.txt .
    - name: Codecov
      uses: codecov/codecov-action@v5
      with:
        flags: general
        name: general

  testDynamodb:
    name: Test with AWS DynamoDB
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go env
      uses: actions/setup-go@v5
      with:
        go-version: ^1.13
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Start AWS DynamoDB local server
      run: docker run -d --name dynamodb -p 8000:8000 amazon/dynamodb-local -jar DynamoDBLocal.jar -inMemory -sharedDb
    - name: Test
      run: |
        export AWS_REGION="us-west-2"
        export AWS_ACCESS_KEY_ID="DUMMYIDEXAMPLE"
        export AWS_SECRET_ACCESS_KEY="DUMMYEXAMPLEKEY"
        export AWS_DYNAMODB_ENDPOINT="http://localhost:8000"
        go test -v -count 1 -p 1 -cover -coverprofile=coverage_dynamodb.txt ./dynamodb
    - name: Codecov
      uses: codecov/codecov-action@v5
      with:
        flags: dynamodb
        name: dynamodb
